name: Upload my site to S3 using a dockerized pyhon script
description: This action uploads files to an S3 bucket using a dockerized python script.

inputs:

  bucket-name:
    description: The name of the S3 bucket to deploy to
    required: true
  region:
    description: The AWS region where the S3 bucket is located
    required: false
    default: 'us-east-1'
  source-dir:
    description: The directory containing the website files to deploy
    required: false
    default: 'dist'
outputs:
  website-url:
    description: The URL of the deployed website.

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucket-name }}